#ifndef HYDROGEN_SRC_SEMANTICS_BUILTINMETHOD
#define HYDROGEN_SRC_SEMANTICS_BUILTINMETHOD
#include"src/basic/global.h"
HYDROGEN_BEGIN_NAMESPACE
enum BuiltInMethodKind
{
    
};
HYDROGEN_END_NAMESPACE

#endif /* HYDROGEN_SRC_SEMANTICS_BUILTINMETHOD */
